version: 2
updates:
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: 4.0.x
    labels:
      - "type: dependency upgrade"
  - package-ecosystem: gradle
    directory: "/"
    schedule:
      interval: daily
    open-pull-requests-limit: 10
    target-branch: 5.1.x
    labels:
      - "type: dependency upgrade"
