name: "Release Drafter"
on:
  issues:
    types: [closed,reopened]
  push:
    branches:
      - master
      - '[4-9]+.[0-9]+.x'
      - '[3-9]+.[3-9]+.x'
  pull_request:
    types: [opened, reopened, synchronize, labeled]
  pull_request_target:
    types: [opened, reopened, synchronize, labeled]
  workflow_dispatch:
permissions:
  contents: read # limit to read access
jobs:
  update_release_draft:
    permissions:
      contents: read # limit to read access
      pull-requests: write # write permission is required for auto labeler
    runs-on: ubuntu-latest
    steps:
      - name: "ğŸ“ Update Release Draft"
        uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}